import React, { useState } from 'react';
import { Alert, RiskLevel, RiskZone } from '../../types';
import { api } from '../../services/api';
import {
  Bell,
  AlertTriangle,
  Flame,
  ShieldAlert,
  Filter,
  Plus,
  Info,
  CheckCircle,
  MapPin,
  Clock,
  Send,
  X,
} from 'lucide-react';

interface AlertsViewProps {
  alerts: Alert[];
  riskZones: RiskZone[];
  onRefreshAlerts: () => void;
  onNavigateToImpact: (zone: RiskZone) => void;
}

export const AlertsView: React.FC<AlertsViewProps> = ({
  alerts,
  riskZones,
  onRefreshAlerts,
  onNavigateToImpact,
}) => {
  const [selectedSeverity, setSelectedSeverity] = useState<string>('ALL');
  const [showCreateModal, setShowCreateModal] = useState<boolean>(false);

  // Modal form state
  const [formZoneId, setFormZoneId] = useState<string>(riskZones[0]?.id || '');
  const [formCategory, setFormCategory] = useState<RiskLevel>('HIGH');
  const [formReason, setFormReason] = useState<string>(
    'Intense monsoon precipitation exceeding 110 mm/24h combined with steep slope shear stress'
  );
  const [formAction, setFormAction] = useState<string>(
    'Deploy local rapid response team, inspect NH-10 culverts, and notify vulnerable ward councils'
  );
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  const filteredAlerts = alerts.filter((a) => {
    if (selectedSeverity === 'ALL') return true;
    return a.riskCategory === selectedSeverity;
  });

  const handleCreateAlert = async (e: React.FormEvent) => {
    e.preventDefault();
    const zone = riskZones.find((z) => z.id === formZoneId) || riskZones[0];
    if (!zone) return;

    setIsSubmitting(true);
    try {
      await api.createAlert({
        zoneId: zone.id,
        locationName: zone.name,
        state: zone.state,
        district: zone.district,
        riskCategory: formCategory,
        probability: formCategory === 'CRITICAL' ? 0.92 : formCategory === 'HIGH' ? 0.76 : 0.48,
        priorityLevel: formCategory === 'CRITICAL' ? 'P1' : 'P2',
        affectedVillages: [zone.name + ' Lower Ward', zone.name + ' Basti'],
        affectedInfrastructure: ['District Lifeline Road', 'Primary Health Sub-Center'],
        primaryReasons: [formReason],
        recommendedActions: [formAction],
      });
      setShowCreateModal(false);
      onRefreshAlerts();
    } catch (err) {
      console.error('Failed to issue prototype alert:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="p-4 space-y-4 max-w-7xl mx-auto w-full">
      {/* Header & Generate Alert Action */}
      <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 shadow-md flex flex-wrap items-center justify-between gap-3">
        <div>
          <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/30">
            Early Warning Feeds
          </span>
          <h2 className="text-xl font-black text-white mt-1 flex items-center gap-2">
            <Bell className="w-5 h-5 text-rose-500" />
            Landslide Hazard Early Warning Advisories
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Active early warning notifications generated by the predictive intelligence engine.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowCreateModal(true)}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-semibold text-xs transition shadow-lg shadow-rose-950/50"
          >
            <Plus className="w-4 h-4" />
            <span>Generate Prototype Alert</span>
          </button>
        </div>
      </div>

      {/* Mandatory Prototype Disclaimer */}
      <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/30 text-xs text-amber-200 flex items-start gap-2.5">
        <Info className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <p className="text-[11px] leading-relaxed">
          <strong>Decision-Support Advisory Notice:</strong> All LANDGUARD alerts are prototype automated warning outputs synthesized from hydro-meteorological models and spatial infrastructure overlays. They assist disaster authorities in prioritizing ground inspections. Official disaster declarations and evacuation mandates remain under State Disaster Management Authorities (SDMA).
        </p>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-2">
        <span className="text-xs text-slate-400 font-medium">Filter Severity:</span>
        {(['ALL', 'CRITICAL', 'HIGH', 'MODERATE', 'LOW'] as const).map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedSeverity(cat)}
            className={`px-3 py-1 rounded-lg text-xs font-semibold transition ${
              selectedSeverity === cat
                ? cat === 'CRITICAL'
                  ? 'bg-red-600 text-white'
                  : cat === 'HIGH'
                  ? 'bg-orange-500 text-white'
                  : 'bg-slate-700 text-white'
                : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
            }`}
          >
            {cat} {cat === 'ALL' ? `(${alerts.length})` : ''}
          </button>
        ))}
      </div>

      {/* Alerts Grid */}
      <div className="space-y-3">
        {filteredAlerts.length > 0 ? (
          filteredAlerts.map((alert) => {
            const isCritical = alert.riskCategory === 'CRITICAL';
            const isHigh = alert.riskCategory === 'HIGH';
            const matchedZone = riskZones.find((z) => z.id === alert.zoneId);

            return (
              <div
                key={alert.id}
                className={`p-4 rounded-xl bg-slate-900 border transition shadow-lg space-y-3 ${
                  isCritical
                    ? 'border-red-500/50 hover:border-red-500'
                    : isHigh
                    ? 'border-orange-500/40 hover:border-orange-500'
                    : 'border-slate-800 hover:border-slate-700'
                }`}
              >
                {/* Alert Header */}
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <span
                      className={`p-1.5 rounded-lg ${
                        isCritical
                          ? 'bg-red-500/20 text-red-400'
                          : 'bg-orange-500/20 text-orange-400'
                      }`}
                    >
                      {isCritical ? <Flame className="w-4 h-4" /> : <AlertTriangle className="w-4 h-4" />}
                    </span>
                    <div>
                      <h3 className="text-sm font-bold text-white">{alert.title}</h3>
                      <div className="text-xs text-slate-400 flex items-center gap-2 mt-0.5">
                        <span className="flex items-center gap-1">
                          <MapPin className="w-3 h-3 text-slate-500" />
                          {alert.locationName}, {alert.district}, {alert.state}
                        </span>
                        <span>&bull;</span>
                        <span className="flex items-center gap-1">
                          <Clock className="w-3 h-3 text-slate-500" />
                          Issued: {new Date(alert.issuedAt).toLocaleString()}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <span
                      className={`px-2.5 py-1 rounded text-xs font-black ${
                        isCritical
                          ? 'bg-red-500/20 text-red-300 border border-red-500/40'
                          : 'bg-orange-500/20 text-orange-300 border border-orange-500/40'
                      }`}
                    >
                      {alert.riskCategory} HAZARD
                    </span>
                    <span className="px-2 py-1 rounded text-xs font-mono bg-slate-800 text-slate-300">
                      Priority {alert.priorityLevel}
                    </span>
                  </div>
                </div>

                {/* Primary Reasons & Recommended Actions */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs pt-1">
                  <div className="p-3 rounded-lg bg-slate-950/80 border border-slate-800 space-y-1">
                    <span className="font-bold text-slate-300 block">Primary Triggers & Telemetry:</span>
                    <ul className="list-disc list-inside text-slate-400 space-y-0.5">
                      {alert.primaryReasons.map((r, i) => (
                        <li key={i}>{r}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="p-3 rounded-lg bg-slate-950/80 border border-slate-800 space-y-1">
                    <span className="font-bold text-slate-300 block">
                      Recommended Preparedness Responses:
                    </span>
                    <ul className="list-disc list-inside text-slate-400 space-y-0.5">
                      {alert.recommendedActions.map((a, i) => (
                        <li key={i}>{a}</li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Footer with Affected Habitations & Action */}
                <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-slate-800/80 text-xs">
                  <div className="text-slate-400">
                    <span className="font-semibold text-slate-300">Monitored Assets: </span>
                    {alert.affectedVillages.concat(alert.affectedInfrastructure).join(', ')}
                  </div>

                  {matchedZone && (
                    <button
                      onClick={() => onNavigateToImpact(matchedZone)}
                      className="px-3 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition"
                    >
                      Inspect Geographic Sector &rarr;
                    </button>
                  )}
                </div>
              </div>
            );
          })
        ) : (
          <div className="p-12 text-center text-slate-500 rounded-xl bg-slate-900 border border-slate-800">
            <CheckCircle className="w-10 h-10 mx-auto text-emerald-500/50 mb-2" />
            <p className="text-sm font-semibold text-slate-300">No active alerts matching filter.</p>
            <p className="text-xs text-slate-500 mt-1">All monitored sectors within acceptable safe thresholds.</p>
          </div>
        )}
      </div>

      {/* Generate Prototype Alert Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
          <div className="w-full max-w-lg rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl p-5 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="font-bold text-base text-white flex items-center gap-2">
                <Bell className="w-4 h-4 text-rose-500" />
                Generate Prototype Early Warning Alert
              </h3>
              <button
                onClick={() => setShowCreateModal(false)}
                className="text-slate-400 hover:text-white transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateAlert} className="space-y-3 text-xs">
              <div>
                <label className="block text-slate-300 font-medium mb-1">Target Sector:</label>
                <select
                  value={formZoneId}
                  onChange={(e) => setFormZoneId(e.target.value)}
                  className="w-full p-2 rounded-lg bg-slate-950 border border-slate-800 text-white focus:outline-none focus:border-rose-500"
                >
                  {riskZones.map((z) => (
                    <option key={z.id} value={z.id}>
                      {z.name} ({z.district}, {z.state})
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-slate-300 font-medium mb-1">Severity Category:</label>
                <div className="grid grid-cols-3 gap-2">
                  {(['CRITICAL', 'HIGH', 'MODERATE'] as const).map((cat) => (
                    <button
                      key={cat}
                      type="button"
                      onClick={() => setFormCategory(cat)}
                      className={`py-1.5 rounded-lg font-bold transition ${
                        formCategory === cat
                          ? cat === 'CRITICAL'
                            ? 'bg-red-600 text-white'
                            : 'bg-orange-600 text-white'
                          : 'bg-slate-950 text-slate-400 border border-slate-800'
                      }`}
                    >
                      {cat}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-slate-300 font-medium mb-1">Primary Warning Triggers:</label>
                <textarea
                  rows={2}
                  value={formReason}
                  onChange={(e) => setFormReason(e.target.value)}
                  className="w-full p-2 rounded-lg bg-slate-950 border border-slate-800 text-white focus:outline-none focus:border-rose-500"
                />
              </div>

              <div>
                <label className="block text-slate-300 font-medium mb-1">Recommended Response Actions:</label>
                <textarea
                  rows={2}
                  value={formAction}
                  onChange={(e) => setFormAction(e.target.value)}
                  className="w-full p-2 rounded-lg bg-slate-950 border border-slate-800 text-white focus:outline-none focus:border-rose-500"
                />
              </div>

              <div className="pt-2 flex justify-end gap-2 border-t border-slate-800">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 font-medium"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-4 py-2 rounded-lg bg-rose-600 hover:bg-rose-500 text-white font-bold flex items-center gap-1.5 disabled:opacity-50"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>Issue Prototype Warning</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
